language: php
php:
  - 5.2
  - 5.3
  - 5.4
before_script:
  - cd lib
  - wget http://downloads.sourceforge.net/project/simpletest/simpletest/simpletest_1.1/simpletest_1.1.0.tar.gz
  - tar -xvzf simpletest_1.1.0.tar.gz > /dev/null 2>&1 &
  - rm simpletest/test -R
  - wget http://www.smarty.net/files/Smarty-3.1.8.tar.gz
  - tar -xvzf Smarty-3.1.8.tar.gz > /dev/null 2>&1 &
  - mv Smarty-3.1.8/libs/ ./Smarty
  - wget http://downloads.sourceforge.net/project/phemto/phemto_0.1_alpha10.tar.gz
  - tar -xvzf phemto_0.1_alpha10.tar.gz > /dev/null 2>&1 &
  - pear install --alldeps HTTP
  - pear install --alldeps Translation2
  - pear install --alldeps --force XML_Serializer
  - pear channel-discover zend.googlecode.com/svn
  - pear install zend/zend
  - pear channel-discover pearhub.org
  - pear install pearhub.org/bucket
  - phpenv rehash
  - cd ..
script: php script/test_all.php --verbose
